name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  convert_api:
    path: ../
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
